# Generated by Django 3.1.3 on 2020-12-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feeds',
        ),
    ]
