# Generated by Django 3.1.3 on 2020-12-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tec', '0002_auto_20201207_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feeds',
            new_name='feedback',
        ),
    ]
